sudo: required
language: generic
services:
  - docker
env:
  HELM_VERSION: v2.14.2
  HELM: $HOME/bin/helm
  CHANGE_MINIKUBE_NONE_USER: true

before_install:
  - docker --version
  - mkdir -p "$HOME/bin";
  - export PATH="$HOME/bin:$PATH";
  - curl -L https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz | tar -xz -C $HOME/bin --strip-components 1
  - chmod +x $HELM;
  - $HELM version -c
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x kubectl
  - mv kubectl $HOME/bin/
  - curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
  - chmod +x minikube
  - mv minikube $HOME/bin/
  - sudo systemctl start docker
  - sudo $HOME/bin/minikube start --vm-driver=none
  - $HOME/bin/minikube update-context
  - JSONPATH='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status};{end}{end}'; \
      until $HOME/bin/kubectl get nodes -o jsonpath="$JSONPATH" 2>&1 | grep -q "Ready=True"; do sleep 1; done
script:
  - find `ls charts/*/Chart.yaml | cut -d'/' -f-2` -name 'value*.yaml' -execdir helm lint -f {} \;
