sudo: required
language: generic
dist: xenial
services:
  - docker
env:
  HELM_VERSION: v2.14.2
  HELMFILE_VERSION: v0.80.1
  CHANGE_MINIKUBE_NONE_USER: true
  HELM: $HOME/bin/helm
  MINIKUBE: $HOME/bin/minikube
  KUBECTL: $HOME/bin/kubectl
  HELMFILE: $HOME/bin/helmfile

before_install:
  - docker --version
  - mkdir -p "$HOME/bin";
  - export PATH="$HOME/bin:$PATH";
  - curl -L https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz | tar -xz -C $HOME/bin --strip-components 1
  - chmod +x $HELM;
  - $HELM version -c
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x kubectl
  - mv kubectl $HOME/bin/
  - curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
  - chmod +x minikube
  - mv minikube $HOME/bin/
  - curl -Lo helmfile https://github.com/roboll/helmfile/releases/download/$HELMFILE_VERSION/helmfile_linux_amd64
  - chmod +x helmfile
  - mv helmfile $HOME/bin/
  - sudo $MINIKUBE start --vm-driver=none
  - $MINIKUBE update-context
  - $KUBECTL version
  - $KUBECTL get nodes

script:
  - find `ls charts/*/Chart.yaml | cut -d'/' -f-2` -name 'value*.yaml' -execdir helm lint -f {} \;
  - git clone https://github.com/RADAR-base/cp-helm-charts.git
  - cp env.template .env
  - source .env
  - ./bin/keystore-init
  - helmfile sync --concurrency 1
