helmDefaults:
  atomic: true
  timeout: 550

releases:
  - name: hdfs-namenode
    chart: ../charts/hdfs
    installed: {{ requiredEnv "RADAR_INSTALL_HDFS" }}
    values:
    - "../charts/hdfs/values-namenode.yaml"
    set:
      - name: image.tag
        value: "{{ requiredEnv "HDFS_IMAGE_TAG" }}"
      - name: replicaCount
        value: "{{ requiredEnv "HDFS_NAMENODE_REPLICA_COUNT" }}"
      - name: volumes[0].size
        value: "{{ requiredEnv "HDFS_NAMENODE_1_DISK_SIZE" }}"
      - name: volumes[1].size
        value: "{{ requiredEnv "HDFS_NAMENODE_2_DISK_SIZE" }}"
  - name: hdfs-datanode
    chart: ../charts/hdfs
    installed: {{ requiredEnv "RADAR_INSTALL_HDFS" }}
    values:
    - "../charts/hdfs/values-datanode.yaml"
    set:
      - name: image.tag
        value: "{{ requiredEnv "HDFS_IMAGE_TAG" }}"
      - name: replicaCount
        value: "{{ requiredEnv "HDFS_DATANODE_REPLICA_COUNT" }}"
      - name: volumes[0].size
        value: "{{ requiredEnv "HDFS_DATANODE_DISK_SIZE" }}"
  - name: radar-connect-hdfs-sink
    chart: ../charts/radar-connect-hdfs-sink
    installed: {{ requiredEnv "RADAR_INSTALL_HDFS" }}
    set:
      - name: image.tag
        value: "{{ requiredEnv "RADAR_CONNECT_HDFS_SINK_IMAGE_TAG" }}"
      - name: replicaCount
        value: "{{ requiredEnv "RADAR_CONNECT_HDFS_SINK_REPLICA_COUNT" }}"
      - name: kafka_num_brokers
        value: "{{ requiredEnv "KAFKA_NUM_BROKERS" }}"
  - name: radar-output
    chart: ../charts/radar-output
    installed: {{ requiredEnv "RADAR_INSTALL_HDFS" }}
    set:
      - name: image.tag
        value: "{{ requiredEnv "RADAR_OUTPUT_IMAGE_TAG" }}"
      - name: replicaCount
        value: "{{ requiredEnv "RADAR_OUTPUT_REPLICA_COUNT" }}"
      - name: num_threads
        value: "{{ requiredEnv "RESTRUCTURE_NUM_THREADS" }}"
      - name: sftp_user_keys
        value: "{{ requiredEnv "RADAR_OUTPUT_SFTP_PUBLIC_KEY" }}"
      - name: persistence.size
        value: "{{ requiredEnv "RADAR_OUTPUT_DISK_SIZE" }}"
