helmDefaults:
  atomic: true
  timeout: 550

releases:
  - name: radar-integration
    chart: ../charts/radar-integration
    installed: {{ requiredEnv "RADAR_INSTALL_REDCAP" }}
    set:
      - name: image.tag
        value: "{{ requiredEnv "RADAR_INTEGRATION_IMAGE_TAG" }}"
      - name: replicaCount
        value: "{{ requiredEnv "RADAR_INTEGRATION_REPLICA_COUNT" }}"
