apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "radar-fitbit-connector.fullname" . }}-properties
  labels:
    app: {{ template "radar-fitbit-connector.name" . }}
    chart: {{ template "radar-fitbit-connector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  source-fitbit.properties: |
    name=radar-fitbit-source
    connector.class=org.radarbase.connect.rest.fitbit.FitbitSourceConnector
    tasks.max={{ .Values.connector_num_tasks }}
    rest.source.base.url=https://api.fitbit.com
    rest.source.poll.interval.ms=5000
    rest.source.request.generator.class=org.radarbase.connect.rest.fitbit.request.FitbitRequestGenerator
    fitbit.api.client={{ .Values.fitbit_api_client }}
    fitbit.api.secret={{ .Values.fitbit_api_secret }}
    fitbit.api.intraday={{ .Values.includeIntradayData }}
    fitbit.user.repository.class=org.radarbase.connect.rest.fitbit.user.ServiceUserRepository
    fitbit.user.repository.url={{ .Values.radar_rest_sources_backend_url }}
    fitbit.user.repository.client.id={{ .Values.oauthClientId }}
    fitbit.user.repository.client.secret={{ .Values.oauthClientSecret }}
    fitbit.user.repository.oauth2.token.url=http://{{ .Values.managementportal_host }}:8080/managementportal/oauth/token

