apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "radar-fitbit-connector.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "radar-fitbit-connector.name" . }}
    helm.sh/chart: {{ include "radar-fitbit-connector.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "radar-fitbit-connector.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxUnavailable: 100%
  template:
    metadata:
      annotations:
        checksum/configmap-properties: {{ include (print $.Template.BasePath "/configmap-properties.yaml") . | sha256sum }}
        checksum/configmap-users: {{ include (print $.Template.BasePath "/configmap-users.yaml") . | sha256sum }}
        backup.velero.io/backup-volumes: logs
      labels:
        app.kubernetes.io/name: {{ include "radar-fitbit-connector.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: "app.kubernetes.io/name"
                    operator: In
                    values:
                    - {{ template "radar-fitbit-connector.name" . }}
                  - key: "app.kubernetes.io/instance"
                    operator: In
                    values:
                    - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: CONNECT_BOOTSTRAP_SERVERS
            value: "{{ .Values.kafka }}"
          - name: CONNECT_REST_PORT
            value: "8083"
          - name: CONNECT_GROUP_ID
            value: "default"
          - name: CONNECT_CONFIG_STORAGE_TOPIC
            value: "default.config"
          - name: CONNECT_OFFSET_STORAGE_TOPIC
            value: "default.offsets"
          - name: CONNECT_STATUS_STORAGE_TOPIC
            value: "default.status"
          - name: CONNECT_KEY_CONVERTER
            value: "io.confluent.connect.avro.AvroConverter"
          - name: CONNECT_VALUE_CONVERTER
            value: "io.confluent.connect.avro.AvroConverter"
          - name: CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL
            value: "{{ .Values.schema_registry }}"
          - name: CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL
            value: "{{ .Values.schema_registry }}"
          - name: CONNECT_INTERNAL_KEY_CONVERTER
            value: "org.apache.kafka.connect.json.JsonConverter"
          - name: CONNECT_INTERNAL_VALUE_CONVERTER
            value: "org.apache.kafka.connect.json.JsonConverter"
          - name: CONNECT_OFFSET_STORAGE_FILE_FILENAME
            value: "/var/lib/kafka-connect-fitbit-source/logs/connect.offsets"
          - name: CONNECT_REST_ADVERTISED_HOST_NAME
            value: {{ include "radar-fitbit-connector.fullname" . }}
          - name: CONNECT_ZOOKEEPER_CONNECT
            value: "{{ .Values.zookeeper }}"
          - name: CONNECTOR_PROPERTY_FILE_PREFIX
            value: "source-fitbit"
          - name: KAFKA_HEAP_OPTS
            value: "-Xms256m -Xmx768m"
          - name: KAFKA_BROKERS
            value: "{{ .Values.kafka_num_brokers }}"
          - name: CONNECT_LOG4J_LOGGERS
            value: "org.reflections=ERROR"
          # - name: CONNECT_NAME
          #   value: "radar-fitbit-source"
          # - name: CONNECT_CONNECTOR_CLASS
          #   value: "org.radarbase.connect.rest.fitbit.FitbitSourceConnector"
          # - name: CONNECT_TASKS_MAX
          #   value: "4"
          # - name: CONNECT_REST_SOURCE_BASE_URL
          #   value: "https://api.fitbit.com"
          # - name: CONNECT_REST_SOURCE_POLL_INTERVAL_MS
          #   value: "5000"
          # - name: CONNECT_REST_SOURCE_REQUEST_GENERATOR_CLASS
          #   value: "org.radarbase.connect.rest.fitbit.request.FitbitRequestGenerator"
          # - name: CONNECT_FITBIT_API_CLIENT
          #   value: "{{ .Values.fitbit_api_client }}"
          # - name: CONNECT_FITBIT_API_SECRET
          #   value: "{{ .Values.fitbit_api_secret }}"
          # - name: CONNECT_FITBIT_USER_REPOSITORY_CLASS
          #   value: "org.radarbase.connect.rest.fitbit.user.ServiceUserRepository"
          # - name: CONNECT_FITBIT_USER_REPOSITORY_URL
          #   value: "http://{{ .Values.radar_rest_sources_backend }}:8080/"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - curl -sf localhost:8083/connectors/radar-fitbit-source/status | grep -o '\"state\":\"[^\"]*\"' | tr '\\n' ',' | grep -vq FAILED || exit 1
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - curl -sf localhost:8083/connectors/radar-fitbit-source/status | grep -o '\"state\":\"[^\"]*\"' | tr '\\n' ',' | grep -vq FAILED || exit 1
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config-properties
              mountPath: /etc/kafka-connect/source-fitbit
            - name: config-users
              mountPath: /var/lib/kafka-connect-fitbit-source/users
            - name: logs
              mountPath: /var/lib/kafka-connect-fitbit-source/logs
      {{- if .Values.persistence.fsUserOverride }}
      initContainers:
      - name: fix-permissions
        command:
        - chown
        - -R
        - {{ .Values.persistence.fsUserOverride }}
        - /var/lib/kafka-connect-fitbit-source/logs
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /var/lib/kafka-connect-fitbit-source/logs
          name: logs
      {{- end }}
      volumes:
        - name: config-properties
          configMap:
            name: {{ include "radar-fitbit-connector.fullname" . }}-properties
        - name: config-users
          configMap:
            name: {{ include "radar-fitbit-connector.fullname" . }}-users
        - name: logs
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "radar-fitbit-connector.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
